import Head from 'next/head'
import { Container, Box } from '@chakra-ui/react'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box borderRadius="lg" bg="red" p={3} mb={6} mt={20} align="center">
          Hello your muscle!!
        </Box>
      </main>

      <footer>
        Powerd by Kazuki Shimamoto
      </footer>
    </Container>
  )
}
